### ISSUE TITLE
React App not Found after refresh (F5)

### ISSUE THREAD

**Issue by luizcarlospedrosogomes** [SAP-samples/btp-launchpad-ui-samples#9]
starting app
![image](https://user-images.githubusercontent.com/9791364/195373299-985404e3-d2c6-41bb-a874-66f6d6fee961.png)

navigate to
![image](https://user-images.githubusercontent.com/9791364/195373475-b80223ca-4515-4ba7-9412-d22375038fff.png)

after press F5
![image](https://user-images.githubusercontent.com/9791364/195373609-6c4db87e-2a07-4d71-a404-14f1d57c9d73.png)

**Comment by MatthiasSchmalz** [comment]
Hi @luizcarlospedrosogomes,

why have your opened this issue in this repository? It does not seem to be related at all.  
I have no samples for react apps.  
Also with these limited details nobody will be able to help.

Best regards  
Matthias

**Comment by luizcarlospedrosogomes** [comment]
Hi @MatthiasSchmalz 

This is a launchpad example repository, right?
For those who want to help are not limited, this happens with any application within BTP! just try to reproduce
Alias should have examples closer to reality, more complex, the real world goes beyond a hello word

Best regards
LCPG

**Comment by MatthiasSchmalz** [comment]
Hi [**@luizcarlospedrosogomes**](https://github.com/luizcarlospedrosogomes),

this repository holds the samples for my blog post that is linked on the readme.md.  
The scope of it is just the scope of the blog but nothing else.

Also your problem is not reproducible for me. Please open a customer support ticket and provide proper reproduction steps.

Best regards  
Matthias
